[package]
name = "maeriil/jecs-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
jecs = "ukendio/jecs@0.5.3"
jabby = "alicesaidhi/jabby@0.2.0-rc.8"
